project:
  type: website

website:
  title: "Bella Shi's Website"
  sidebar:
    contents: 
      - text: "Introduction"
        href: index.qmd
      - text: About me
        href: https://bella.georgetown.domains/about/
      - ARM.qmd
      - Classfication.qmd
      - Cleaning.ipynb
      - Clustering.qmd
      - Code.qmd
      - Conclusions.qmd
      - Data.qmd
      - Dimensionality reduction.qmd
      - Exploration.qmd
      - Gathering.ipynb
      - Regression.qmd


format:
  html:
    theme: cosmo
    toc: true



