project:
  type: website

website:
  title: "5000  Project"
  sidebar:
    contents: 
      - introduction.qmd
      - about.qmd
      - ARM.qmd
      - Classfication.qmd
      - Cleaning.qmd
      - Clustering.qmd
      - Code.qmd
      - Conclusions.qmd
      - Data.qmd
      - Dimensionality reduction.qmd
      - Exploration.qmd
      - gathering.qmd
      - Regression.qmd


format:
  html:
    theme: cosmo
    toc: true



