project:
  type: website

website:
  title: "Bella Shi's Website"
  sidebar:
    contents: 
      - text: 'Introduction'
        href: index.qmd
      - text: About me
        href: https://bella.georgetown.domains/about/
      - Code.qmd
      - Data.qmd
      - Gathering.ipynb
      - Cleaning.ipynb
      - Exploration.ipynb
      - Naive Bayes.ipynb
      - Clustering.qmd
      - Classfication.qmd
      - Dimensionality reduction.qmd
      - Regression.qmd
      - ARM.qmd
      - Conclusions.qmd


format:
  html:
    theme: cosmo
    toc: true



