project:
  type: website

website:
  title: "Bella Shi's Website"
  sidebar:
    contents: 
      - text: Introduction
        href: index.qmd
      - about.qmd
      # - text: About me
      #   href: https://bella.georgetown.domains/about/my_website/
      - text : Code
        href: https://github.com/anly501/dsan-5000-project-bella20000605
      - Data.qmd
      - Gathering.ipynb
      - Cleaning.ipynb
      - Exploration.ipynb
      - Naive Bayes.ipynb
      - reduction.ipynb
      - Clustering.ipynb
      - DT.ipynb
      - ARM.qmd
      - Conclusions.qmd
      - References.ipynb

format:
  html:
    theme: [quartz, theme.scss]
    toc: true



