<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bella Shi’s Website - Exploration</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Exploration.html">Exploration</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bella Shi’s Website</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About me</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://github.com/anly501/dsan-5000-project-bella20000605" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Code</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Gathering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Gathering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Cleaning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Exploration.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Exploration</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Naive Bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Naive Bayes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dimensionality Reduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clustering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decision Trees</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ARM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ARM and Networking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data-understanding" id="toc-data-understanding" class="nav-link active" data-scroll-target="#data-understanding">Data Understanding</a></li>
  <li><a href="#descriptive-statistics-data-visualization-corralation-analysis-data-grouping-and-segmentation" id="toc-descriptive-statistics-data-visualization-corralation-analysis-data-grouping-and-segmentation" class="nav-link" data-scroll-target="#descriptive-statistics-data-visualization-corralation-analysis-data-grouping-and-segmentation">Descriptive Statistics &amp; Data Visualization &amp; Corralation Analysis &amp; Data Grouping and Segmentation</a>
  <ul class="collapse">
  <li><a href="#mental-health-dataset" id="toc-mental-health-dataset" class="nav-link" data-scroll-target="#mental-health-dataset">1.Mental Health Dataset</a></li>
  <li><a href="#eating-disorder-dataset" id="toc-eating-disorder-dataset" class="nav-link" data-scroll-target="#eating-disorder-dataset">2.Eating disorder Dataset</a></li>
  <li><a href="#age-when-first-have-depression-or-anxiety-data" id="toc-age-when-first-have-depression-or-anxiety-data" class="nav-link" data-scroll-target="#age-when-first-have-depression-or-anxiety-data">3.Age when first have depression or anxiety Data</a></li>
  </ul></li>
  <li><a href="#hypothesis-generation" id="toc-hypothesis-generation" class="nav-link" data-scroll-target="#hypothesis-generation">Hypothesis Generation</a>
  <ul class="collapse">
  <li><a href="#age-first-depression-or-anxiety-data" id="toc-age-first-depression-or-anxiety-data" class="nav-link" data-scroll-target="#age-first-depression-or-anxiety-data">Age First Depression or Anxiety Data</a></li>
  <li><a href="#eating-disorder-dataset-1" id="toc-eating-disorder-dataset-1" class="nav-link" data-scroll-target="#eating-disorder-dataset-1">Eating disorder Dataset</a></li>
  <li><a href="#mental-health-dataset-1" id="toc-mental-health-dataset-1" class="nav-link" data-scroll-target="#mental-health-dataset-1">Mental Health Dataset</a></li>
  </ul></li>
  <li><a href="#report-and-discuss-methods-and-findings" id="toc-report-and-discuss-methods-and-findings" class="nav-link" data-scroll-target="#report-and-discuss-methods-and-findings">Report and Discuss methods and findings</a></li>
  <li><a href="#tools-and-software" id="toc-tools-and-software" class="nav-link" data-scroll-target="#tools-and-software">Tools and Software</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploration</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell" data-execution_count="534">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#load the data sets</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df_age_first_depression<span class="op">=</span>pd.read_csv(<span class="st">'./Data_cleaned/age_when_first_anxiety_or_depression.csv'</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df_eating_disorder<span class="op">=</span>pd.read_csv(<span class="st">'./Data_cleaned/eating_disorder_male_female.csv'</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df_mental_health<span class="op">=</span>pd.read_csv(<span class="st">'./Data_cleaned/mental_health.csv'</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>df_mental_physical<span class="op">=</span>pd.read_csv(<span class="st">'./Data_cleaned/symptoms.csv'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df_gdp_mental_health_2017<span class="op">=</span>pd.read_csv(<span class="st">'./Data/GDP_percaptita_mental_health_2017.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="data-understanding" class="level2">
<h2 class="anchored" data-anchor-id="data-understanding">Data Understanding</h2>
<p><b> 1.Mental Health Dataset</b></p>
<p>The dataset contains various mental health-related metrics for different economies over several years, with information from different years and countries, with percentages for various mental health conditions such as schizophrenia, bipolar disorder, eating disorders, anxiety disorders, and depression. Additional columns include economic indicators like income group, average learning adjusted years of school, continent, GDP for 2022, and a column related to comfort speaking about anxiety or depression, which has many missing values (NaN).</p>
<p>Economy: The name of the economy or country. Code: The country code.</p>
<p>Year: The year of the data record.</p>
<p>Schizophrenia (%): The prevalence of schizophrenia as a percentage. Bipolar disorder (%): The prevalence of bipolar disorder as a percentage.</p>
<p>Eating disorders (%): The prevalence of eating disorders as a percentage.</p>
<p>Anxiety disorders (%): The prevalence of anxiety disorders as a percentage.</p>
<p>Depression (%): The prevalence of depression as a percentage.</p>
<p>Income group: The income group classification of the economy.</p>
<p>average_learning_Adjusted_of_school: Some metric related to schooling, perhaps average years of schooling adjusted for learning.</p>
<p>Continent: The continent where the economy is located.</p>
<p>GDP(2022): The GDP of the economy for the year 2022.</p>
<p>GDP_per_capita(2022): The GDP per capita of the economy.</p>
<p>not_at_all_comfortable_speaking_anxiety_or_depression_percent: The percentage of people not at all comfortable speaking about anxiety or depression</p>
<p>Records: 5,488 Variables: 14 (1 integer, 9 floats, 4 objects) Features: Includes country data, year, percentages for various mental health conditions, income group, average learning, continent, GDP, GDP per capita, and comfort speaking about anxiety/depression.</p>
<div class="cell" data-execution_count="535">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>name<span class="op">=</span><span class="st">'mental_health'</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>df_mental_health</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'mental_health'</span><span class="sc">}</span><span class="ss"> Dataset - First 5 Rows:"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>display(df_mental_health.head())</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset - Info:"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>display(df.info())</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset -Shape:"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>display(df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>mental_health Dataset - First 5 Rows:

mental_health Dataset - Info:
&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 5488 entries, 0 to 5487
Data columns (total 14 columns):
 #   Column                                                         Non-Null Count  Dtype  
---  ------                                                         --------------  -----  
 0   Economy                                                        5488 non-null   object 
 1   Code                                                           5488 non-null   object 
 2   Year                                                           5488 non-null   int64  
 3   Schizophrenia (%)                                              5488 non-null   float64
 4   Bipolar disorder (%)                                           5488 non-null   float64
 5   Eating disorders (%)                                           5488 non-null   float64
 6   Anxiety disorders (%)                                          5488 non-null   float64
 7   Depression (%)                                                 5488 non-null   float64
 8   Income group                                                   5432 non-null   object 
 9   average_learning_Adjusted_of_school                            4676 non-null   float64
 10  Continent                                                      4900 non-null   object 
 11  GDP(2022)                                                      5264 non-null   float64
 12  not_at_all_comfortable_speaking_anxiety_or_depression_percent  3108 non-null   float64
 13  GDP_per_capita                                                 4468 non-null   float64
dtypes: float64(9), int64(1), object(4)
memory usage: 600.4+ KB
mental_health Dataset -Shape:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Economy</th>
<th data-quarto-table-cell-role="th">Code</th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Schizophrenia (%)</th>
<th data-quarto-table-cell-role="th">Bipolar disorder (%)</th>
<th data-quarto-table-cell-role="th">Eating disorders (%)</th>
<th data-quarto-table-cell-role="th">Anxiety disorders (%)</th>
<th data-quarto-table-cell-role="th">Depression (%)</th>
<th data-quarto-table-cell-role="th">Income group</th>
<th data-quarto-table-cell-role="th">average_learning_Adjusted_of_school</th>
<th data-quarto-table-cell-role="th">Continent</th>
<th data-quarto-table-cell-role="th">GDP(2022)</th>
<th data-quarto-table-cell-role="th">not_at_all_comfortable_speaking_anxiety_or_depression_percent</th>
<th data-quarto-table-cell-role="th">GDP_per_capita</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1990</td>
<td>0.160560</td>
<td>0.697779</td>
<td>0.101855</td>
<td>4.828830</td>
<td>4.071831</td>
<td>Low income</td>
<td>4.957542</td>
<td>Asia</td>
<td>14583.0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1991</td>
<td>0.160312</td>
<td>0.697961</td>
<td>0.099313</td>
<td>4.829740</td>
<td>4.079531</td>
<td>Low income</td>
<td>4.957542</td>
<td>Asia</td>
<td>14583.0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1992</td>
<td>0.160135</td>
<td>0.698107</td>
<td>0.096692</td>
<td>4.831108</td>
<td>4.088358</td>
<td>Low income</td>
<td>4.957542</td>
<td>Asia</td>
<td>14583.0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1993</td>
<td>0.160037</td>
<td>0.698257</td>
<td>0.094336</td>
<td>4.830864</td>
<td>4.096190</td>
<td>Low income</td>
<td>4.957542</td>
<td>Asia</td>
<td>14583.0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1994</td>
<td>0.160022</td>
<td>0.698469</td>
<td>0.092439</td>
<td>4.829423</td>
<td>4.099582</td>
<td>Low income</td>
<td>4.957542</td>
<td>Asia</td>
<td>14583.0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>None</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>(5488, 14)</code></pre>
</div>
</div>
<p><b> 2. Eating Disorder Dataset </b></p>
<p>This dataset includes the prevalence of eating disorders among males and females, as well as a combined figure for all genders, across different countries and years.</p>
<p>Country: The name of the country.</p>
<p>Country Code: The corresponding country code.</p>
<p>Year: The year of the observation.</p>
<p>Eating_disorders_Male: The prevalence of eating disorders among males.</p>
<p>Eating_disorders_Female: The prevalence of eating disorders among females.</p>
<p>All_gender: The prevalence of eating disorders across all genders.</p>
<p>Records: 6,420 Variables: 6 (1 integer, 3 floats, 2 objects) Features: Includes country data, year, and eating disorder prevalence separated by male, female, and all genders.</p>
<div class="cell" data-execution_count="536">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>name<span class="op">=</span><span class="st">'eating_disorder'</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>df_eating_disorder</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'eating_disorder'</span><span class="sc">}</span><span class="ss"> Dataset - First 5 Rows:"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>display(df_eating_disorder.head())</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset - Info:"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>display(df.info())</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset -Shape:"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>display(df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>eating_disorder Dataset - First 5 Rows:

eating_disorder Dataset - Info:
&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 6420 entries, 0 to 6419
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Economy                  6420 non-null   object 
 1   Code                     6150 non-null   object 
 2   Year                     6420 non-null   int64  
 3   Eating_disorders_Male    6420 non-null   float64
 4   Eating_disorders_Female  6420 non-null   float64
 5   All_gender               6420 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 301.1+ KB
eating_disorder Dataset -Shape:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Economy</th>
<th data-quarto-table-cell-role="th">Code</th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Eating_disorders_Male</th>
<th data-quarto-table-cell-role="th">Eating_disorders_Female</th>
<th data-quarto-table-cell-role="th">All_gender</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1990</td>
<td>0.088487</td>
<td>0.161867</td>
<td>0.125177</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1991</td>
<td>0.086048</td>
<td>0.156910</td>
<td>0.121479</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1992</td>
<td>0.083625</td>
<td>0.152412</td>
<td>0.118018</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1993</td>
<td>0.081628</td>
<td>0.147938</td>
<td>0.114783</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Afghanistan</td>
<td>AFG</td>
<td>1994</td>
<td>0.079439</td>
<td>0.143980</td>
<td>0.111710</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>None</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>(6420, 6)</code></pre>
</div>
</div>
<p><b> 3. Age When First Anxiety or Depression Dataset</b></p>
<p>The dataset contains information on the age at which individuals first experienced anxiety or depression, categorized by different entities (which seem to represent regions or income categories).</p>
<p>Entity: The region or income category.</p>
<p>Age: The age category when anxiety or depression was first experienced.</p>
<p>Percentage: The percentage of individuals in that entity and age category.</p>
<p>Records: 42 Variables: 3 (2 objects, 1 float) Features: Includes entity (could be country or other types of entities), age category, and percentage of individuals with first anxiety or depression experience.</p>
<div class="cell" data-execution_count="537">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>name<span class="op">=</span><span class="st">'age_first_depression'</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>df_age_first_depression</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'age_first_depression'</span><span class="sc">}</span><span class="ss"> Dataset - First 5 Rows:"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>display(df_age_first_depression.head())</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset - Info:"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>display(df.info())</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset -Shape:"</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>display(df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>age_first_depression Dataset - First 5 Rows:

age_first_depression Dataset - Info:
&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Entity      42 non-null     object 
 1   Age         42 non-null     object 
 2   Percentage  42 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.1+ KB
age_first_depression Dataset -Shape:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Entity</th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Africa</td>
<td>Ages &lt;13</td>
<td>1.271836</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Asia</td>
<td>Ages &lt;13</td>
<td>7.795371</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Europe</td>
<td>Ages &lt;13</td>
<td>9.083381</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>High-income countries</td>
<td>Ages &lt;13</td>
<td>2.473921</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Lower-middle-income countries</td>
<td>Ages &lt;13</td>
<td>8.800553</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>None</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>(42, 3)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="538">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>name<span class="op">=</span><span class="st">'df_gdp_mental_health_2017'</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>df_gdp_mental_health_2017</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'name'</span><span class="sc">}</span><span class="ss"> Dataset - First 5 Rows:"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>display(df.head())</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset - Info:"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>display(df.info())</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset -Shape:"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>display(df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>name Dataset - First 5 Rows:

df_gdp_mental_health_2017 Dataset - Info:
&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 166 entries, 0 to 165
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Economy                166 non-null    object 
 1   2017                   166 non-null    object 
 2   Schizophrenia (%)      166 non-null    float64
 3   Bipolar disorder (%)   166 non-null    float64
 4   Eating disorders (%)   166 non-null    float64
 5   Anxiety disorders (%)  166 non-null    float64
 6   Depression (%)         166 non-null    float64
dtypes: float64(5), object(2)
memory usage: 9.2+ KB
df_gdp_mental_health_2017 Dataset -Shape:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Economy</th>
<th data-quarto-table-cell-role="th">2017</th>
<th data-quarto-table-cell-role="th">Schizophrenia (%)</th>
<th data-quarto-table-cell-role="th">Bipolar disorder (%)</th>
<th data-quarto-table-cell-role="th">Eating disorders (%)</th>
<th data-quarto-table-cell-role="th">Anxiety disorders (%)</th>
<th data-quarto-table-cell-role="th">Depression (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Afghanistan</td>
<td>635.789</td>
<td>0.166158</td>
<td>0.708089</td>
<td>0.107142</td>
<td>4.882481</td>
<td>4.136347</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Albania</td>
<td>4525.887</td>
<td>0.201025</td>
<td>0.704480</td>
<td>0.174046</td>
<td>3.385245</td>
<td>2.208414</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Algeria</td>
<td>4014.707</td>
<td>0.197913</td>
<td>0.818687</td>
<td>0.213612</td>
<td>5.065876</td>
<td>3.661094</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Andorra</td>
<td>40017.741</td>
<td>0.263512</td>
<td>0.963331</td>
<td>0.644559</td>
<td>5.305375</td>
<td>3.729532</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Angola</td>
<td>4039.3</td>
<td>0.172794</td>
<td>0.623904</td>
<td>0.173643</td>
<td>3.296906</td>
<td>4.160484</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>None</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>(166, 7)</code></pre>
</div>
</div>
<p><b> 4.Symtoms dataset</b></p>
<p>This dataset contains 2 columns,one is symtoms of health problem and another is related to the respective health problem(mental or Physical).</p>
<div class="cell" data-execution_count="539">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>name<span class="op">=</span><span class="st">'df_mental_physical'</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>df_mental_physical</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'name'</span><span class="sc">}</span><span class="ss"> Dataset - First 5 Rows:"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>display(df.head())</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset - Info:"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>display(df.info())</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Dataset -Shape:"</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>display(df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>name Dataset - First 5 Rows:

df_mental_physical Dataset - Info:
&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 186 entries, 0 to 185
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  186 non-null    int64 
 1   Symptoms    186 non-null    object
 2   Label       186 non-null    object
dtypes: int64(1), object(2)
memory usage: 4.5+ KB
df_mental_physical Dataset -Shape:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Unnamed: 0</th>
<th data-quarto-table-cell-role="th">Symptoms</th>
<th data-quarto-table-cell-role="th">Label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>I often experience shortness of breath.</td>
<td>Physical health</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>I have been feeling persistent fatigue lately.</td>
<td>Physical health</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2</td>
<td>I am experiencing unexplained weight loss.</td>
<td>Physical health</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>3</td>
<td>I have a consistent cough that won't go away.</td>
<td>Physical health</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>4</td>
<td>I am dealing with frequent headaches.</td>
<td>Physical health</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>None</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>(186, 3)</code></pre>
</div>
</div>
</section>
<section id="descriptive-statistics-data-visualization-corralation-analysis-data-grouping-and-segmentation" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics-data-visualization-corralation-analysis-data-grouping-and-segmentation">Descriptive Statistics &amp; Data Visualization &amp; Corralation Analysis &amp; Data Grouping and Segmentation</h2>
<p>Calculate and report basic summary statistics for the datasets.</p>
<p>This will include mean, median, mode, standard deviation, and variance for numerical variables.</p>
<p>For categorical variables, I will use frequency distributions.​</p>
<div class="cell" data-execution_count="540">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>description_stats<span class="op">=</span>{</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"age_first_depression_or_anxiety"</span>:df_age_first_depression.describe(include<span class="op">=</span><span class="st">'all'</span>),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"eating_disorder"</span>:df_eating_disorder.describe(include<span class="op">=</span><span class="st">'all'</span>),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"mental_health"</span>:df_mental_health.describe(include<span class="op">=</span><span class="st">'all'</span>),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'symptoms_mental_vs_physical'</span>:df_mental_physical.describe(include<span class="op">=</span><span class="st">'all'</span>),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>description_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="540">
<pre><code>{'age_first_depression_or_anxiety':         Entity       Age  Percentage
 count       42        42   42.000000
 unique       7         6         NaN
 top     Africa  Ages &lt;13         NaN
 freq         6         7         NaN
 mean       NaN       NaN   16.666667
 std        NaN       NaN   10.060695
 min        NaN       NaN    1.271836
 25%        NaN       NaN    8.871260
 50%        NaN       NaN   14.426575
 75%        NaN       NaN   22.251861
 max        NaN       NaN   42.724724,
 'eating_disorder':             Economy  Code         Year  Eating_disorders_Male  \
 count          6420  6150  6420.000000            6420.000000   
 unique          214   205          NaN                    NaN   
 top     Afghanistan   AFG          NaN                    NaN   
 freq             30    30          NaN                    NaN   
 mean            NaN   NaN  2004.500000               0.119775   
 std             NaN   NaN     8.656116               0.068943   
 min             NaN   NaN  1990.000000               0.033360   
 25%             NaN   NaN  1997.000000               0.071057   
 50%             NaN   NaN  2004.500000               0.098256   
 75%             NaN   NaN  2012.000000               0.148705   
 max             NaN   NaN  2019.000000               0.672270   
 
         Eating_disorders_Female   All_gender  
 count               6420.000000  6420.000000  
 unique                      NaN          NaN  
 top                         NaN          NaN  
 freq                        NaN          NaN  
 mean                   0.273787     0.196781  
 std                    0.214920     0.140066  
 min                    0.056762     0.045083  
 25%                    0.121105     0.096171  
 50%                    0.187430     0.144395  
 75%                    0.352395     0.252282  
 max                    1.395754     1.034012  ,
 'mental_health':             Economy  Code         Year  Schizophrenia (%)  \
 count          5488  5488  5488.000000        5488.000000   
 unique          196   196          NaN                NaN   
 top     Afghanistan   AFG          NaN                NaN   
 freq             28    28          NaN                NaN   
 mean            NaN   NaN  2003.500000           0.208183   
 std             NaN   NaN     8.078483           0.041998   
 min             NaN   NaN  1990.000000           0.146902   
 25%             NaN   NaN  1996.750000           0.179452   
 50%             NaN   NaN  2003.500000           0.198509   
 75%             NaN   NaN  2010.250000           0.230554   
 max             NaN   NaN  2017.000000           0.375110   
 
         Bipolar disorder (%)  Eating disorders (%)  Anxiety disorders (%)  \
 count            5488.000000           5488.000000            5488.000000   
 unique                   NaN                   NaN                    NaN   
 top                      NaN                   NaN                    NaN   
 freq                     NaN                   NaN                    NaN   
 mean                0.716884              0.234023               3.946979   
 std                 0.164246              0.154147               1.134810   
 min                 0.314535              0.073908               2.023393   
 25%                 0.615732              0.121760               3.178912   
 50%                 0.693954              0.180378               3.515140   
 75%                 0.830217              0.278681               4.659540   
 max                 1.206597              0.943991               8.967330   
 
         Depression (%) Income group  average_learning_Adjusted_of_school  \
 count      5488.000000         5432                          4676.000000   
 unique             NaN            4                                  NaN   
 top                NaN  High income                                  NaN   
 freq               NaN         1764                                  NaN   
 mean          3.474504          NaN                             7.760170   
 std           0.671741          NaN                             2.528810   
 min           2.139903          NaN                             2.251002   
 25%           2.955355          NaN                             5.684793   
 50%           3.461421          NaN                             7.855914   
 75%           3.877343          NaN                            10.048229   
 max           6.602754          NaN                            12.775495   
 
        Continent     GDP(2022)  \
 count       4900  5.264000e+03   
 unique         6           NaN   
 top       Africa           NaN   
 freq        1428           NaN   
 mean         NaN  3.929245e+05   
 std          NaN  1.451071e+06   
 min          NaN  2.230000e+02   
 25%          NaN  1.240875e+04   
 50%          NaN  4.239550e+04   
 75%          NaN  2.550042e+05   
 max          NaN  1.796317e+07   
 
         not_at_all_comfortable_speaking_anxiety_or_depression_percent  \
 count                                         3108.000000               
 unique                                                NaN               
 top                                                   NaN               
 freq                                                  NaN               
 mean                                            30.009805               
 std                                             11.940808               
 min                                              5.833535               
 25%                                             21.170624               
 50%                                             30.920343               
 75%                                             37.729200               
 max                                             58.778120               
 
         GDP_per_capita  
 count      4468.000000  
 unique             NaN  
 top                NaN  
 freq               NaN  
 mean       9957.671571  
 std       15590.325250  
 min          31.321000  
 25%         982.891500  
 50%        3309.844000  
 75%       11159.947250  
 max      125200.137000  ,
 'symptoms_mental_vs_physical':         Unnamed: 0                                 Symptoms            Label
 count   186.000000                                      186              186
 unique         NaN                                      186                2
 top            NaN  I often experience shortness of breath.  Physical health
 freq           NaN                                        1              100
 mean     92.500000                                      NaN              NaN
 std      53.837719                                      NaN              NaN
 min       0.000000                                      NaN              NaN
 25%      46.250000                                      NaN              NaN
 50%      92.500000                                      NaN              NaN
 75%     138.750000                                      NaN              NaN
 max     185.000000                                      NaN              NaN}</code></pre>
</div>
</div>
<section id="mental-health-dataset" class="level3">
<h3 class="anchored" data-anchor-id="mental-health-dataset">1.Mental Health Dataset</h3>
<section id="histograms-plot" class="level4">
<h4 class="anchored" data-anchor-id="histograms-plot">Histograms Plot</h4>
<div class="cell" data-execution_count="541">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the aesthetics for the plots</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to create histograms for given columns</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_histograms(data, columns, bins<span class="op">=</span><span class="dv">20</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">5</span>)):</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="bu">len</span>(columns), figsize<span class="op">=</span>figsize)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ax, col <span class="kw">in</span> <span class="bu">zip</span>(axes, columns):</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>        sns.histplot(data[col].dropna(), bins<span class="op">=</span>bins, ax<span class="op">=</span>ax, kde<span class="op">=</span><span class="va">True</span>)  <span class="co"># Drop NaN for plotting</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>        ax.set_title(<span class="ss">f'Distribution of </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Select columns to plot for Mental Health Data (excluding 'Year' and non-numerical columns)</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>mental_health_columns <span class="op">=</span> [<span class="st">'Schizophrenia (%)'</span>, <span class="st">'Bipolar disorder (%)'</span>, </span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>                         <span class="st">'Eating disorders (%)'</span>, <span class="st">'Anxiety disorders (%)'</span>, <span class="st">'Depression (%)'</span>]</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms for the selected columns</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>histograms_mental_health <span class="op">=</span> plot_histograms(df_mental_health, mental_health_columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="time-series-plot" class="level4">
<h4 class="anchored" data-anchor-id="time-series-plot">Time Series Plot</h4>
<p>To observe the trend of a specific disorder over time aggregated globally.</p>
<div class="cell" data-execution_count="542">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate the data by Year and calculate the mean for each disorder</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>annual_prevalence <span class="op">=</span> df_mental_health.groupby(<span class="st">'Year'</span>).mean().reset_index()</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>annual_prevalence.head()</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine the number of disorders to plot</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>num_disorders <span class="op">=</span> <span class="bu">len</span>(annual_prevalence.columns[<span class="dv">1</span>:<span class="dv">6</span>])</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating subplots</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(num_disorders, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">6</span> <span class="op">*</span> num_disorders))</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting each disorder in a separate subplot</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, column <span class="kw">in</span> <span class="bu">enumerate</span>(annual_prevalence.columns[<span class="dv">1</span>:<span class="dv">6</span>]):</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    axes[i].plot(annual_prevalence[<span class="st">'Year'</span>], annual_prevalence[column], label<span class="op">=</span>column)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    axes[i].set_title(column)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    axes[i].set_xlabel(<span class="st">'Year'</span>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>    axes[i].set_ylabel(<span class="st">'Prevalence (%)'</span>)</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>    axes[i].grid(<span class="va">True</span>)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/527416444.py:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  annual_prevalence = df_mental_health.groupby('Year').mean().reset_index()</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-10-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Anxiety disorders and depression show higher prevalence rates compared to other disorders like schizophrenia, bipolar disorder, and eating disorders.This could indicate that anxiety and depression are more common mental health concerns in the population.</p>
<p>The prevalence rates for disorders like schizophrenia, bipolar disorder, eating disorders and anxiety disorders keep increaseing over the years, while the depression retes does not have a liner increasement.it has a peak in 1997 and then decrease to a lower level.</p>
</section>
<section id="the-bar-plot" class="level4">
<h4 class="anchored" data-anchor-id="the-bar-plot">The Bar plot</h4>
<p>To compare the prevalence of different disorders across different income groups.</p>
<div class="cell" data-execution_count="543">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>df_income_group<span class="op">=</span>df_mental_health.groupby(<span class="st">'Income group'</span>).mean()</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print(df_income_group)</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>df_income_group<span class="op">=</span>df_income_group.drop(columns<span class="op">=</span>[<span class="st">'Year'</span>,<span class="st">'GDP(2022)'</span>,<span class="st">'not_at_all_comfortable_speaking_anxiety_or_depression_percent'</span>,<span class="st">'average_learning_Adjusted_of_school'</span>,<span class="st">'GDP_per_capita'</span>])</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print(type(df_income_group))</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>df_income_group.plot(kind<span class="op">=</span><span class="st">'bar'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Mean Percentage of Mental Health Disorders by Income Group'</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Mean Percentage'</span>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Income Group'</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">'Mental Health Disorders'</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/3638934320.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_income_group=df_mental_health.groupby('Income group').mean()</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-11-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="the-box-plot" class="level4">
<h4 class="anchored" data-anchor-id="the-box-plot">The Box Plot</h4>
<p>Box Plot: Distribution of mental health disorders prevalence rates across different income groups in 2017.</p>
<div class="cell" data-execution_count="544">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming df_mental_health is your DataFrame</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace 'df_mental_health' with the actual name of your DataFrame if different</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>most_recent_year <span class="op">=</span> df_mental_health[<span class="st">'Year'</span>].<span class="bu">max</span>()</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Disorders to plot</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>disorders <span class="op">=</span> [<span class="st">'Bipolar disorder (%)'</span>, <span class="st">'Schizophrenia (%)'</span>, <span class="st">'Eating disorders (%)'</span>, <span class="st">'Anxiety disorders (%)'</span>, <span class="st">'Depression (%)'</span>]</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating box plots for each disorder</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> disorder <span class="kw">in</span> disorders:</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Filter the data for the disorder for the most recent year</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    disorder_data_recent_year <span class="op">=</span> df_mental_health[df_mental_health[<span class="st">'Year'</span>] <span class="op">==</span> most_recent_year]</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>    sns.boxplot(data<span class="op">=</span>disorder_data_recent_year, x<span class="op">=</span><span class="st">'Income group'</span>, y<span class="op">=</span>disorder)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'Distribution of </span><span class="sc">{</span>disorder<span class="sc">}</span><span class="ss"> Across Income Groups in </span><span class="sc">{</span>most_recent_year<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">'Income Group'</span>)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="ss">f'</span><span class="sc">{</span>disorder<span class="sc">}</span><span class="ss"> Prevalence (%)'</span>)</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    plt.grid(axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-12-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-12-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-12-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-12-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-12-output-5.png" class="img-fluid"></p>
</div>
</div>
<p>The plot provides insights into the median prevalence rates, the interquartile ranges, and any potential outliers within each income group category.</p>
<p>The Box Plot above shows the distribution of ‘Bipolar disorder (%)’, ‘Schizophrenia (%)’, ‘Eating disorders (%)’, ’Anxiety disorders (%)’prevalence vary by income group level, while the Depression doesn’t vary by income group level.</p>
</section>
<section id="scatter-plot" class="level4">
<h4 class="anchored" data-anchor-id="scatter-plot">Scatter plot:</h4>
<p>Relationship between ‘average learning adjusted years of school’ and mental health disorders prevalence rates</p>
<div class="cell" data-execution_count="545">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_scatter_plots(dataframe, x_col, y_cols, row_col_count):</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the number of rows and columns needed for the subplots</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    total_plots <span class="op">=</span> <span class="bu">len</span>(y_cols)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    nrows <span class="op">=</span> (total_plots <span class="op">+</span> row_col_count <span class="op">-</span> <span class="dv">1</span>) <span class="op">//</span> row_col_count  <span class="co"># Ceiling division</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    ncols <span class="op">=</span> row_col_count</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create subplots</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(nrows, ncols, figsize<span class="op">=</span>(<span class="dv">15</span>, nrows <span class="op">*</span> <span class="dv">5</span>))</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> nrows <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>        axes <span class="op">=</span> [axes]  <span class="co"># Ensure axes is always a list</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>        axes <span class="op">=</span> axes.flatten()</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate scatter plots</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, y_col <span class="kw">in</span> <span class="bu">enumerate</span>(y_cols):</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>        sns.scatterplot(ax<span class="op">=</span>axes[i], data<span class="op">=</span>dataframe, x<span class="op">=</span>x_col, y<span class="op">=</span>y_col)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>        axes[i].set_title(<span class="ss">f'</span><span class="sc">{</span>y_col<span class="sc">}</span><span class="ss"> vs </span><span class="sc">{</span>x_col<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>        axes[i].set_xlabel(x_col)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>        axes[i].set_ylabel(<span class="ss">f'Prevalence of </span><span class="sc">{</span>y_col<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Hide any unused subplots</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(i<span class="op">+</span><span class="dv">1</span>, <span class="bu">len</span>(axes)):</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>        axes[j].set_visible(<span class="va">False</span>)</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Adjust layout</span></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>education_col <span class="op">=</span> <span class="st">'average_learning_Adjusted_of_school'</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>mental_health_disorders <span class="op">=</span> [</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Schizophrenia (%)'</span>,  <span class="co"># The prevalence of schizophrenia as a percentage</span></span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Bipolar disorder (%)'</span>,  <span class="co"># The prevalence of bipolar disorder as a percentage</span></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Eating disorders (%)'</span>,  <span class="co"># The prevalence of eating disorders as a percentage</span></span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Anxiety disorders (%)'</span> , <span class="co"># The prevalence of anxiety disorders as a percentage</span></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Depression (%)'</span>  <span class="co"># The prevalence of depression as a percentage</span></span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a>create_scatter_plots(df_mental_health, education_col, mental_health_disorders, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Schizophrenia: There appears to be a cluster of points towards the lower end of the educational scale with varying prevalence rates. As education levels increase, the prevalence rates seem to spread out, indicating a less clear relationship.</p>
<p>Bipolar Disorder: The data points are dispersed across the educational spectrum with no clear trend indicating a strong relationship between education and the prevalence of bipolar disorder.</p>
<p>Eating Disorders: This plot shows a somewhat more dispersed distribution, suggesting that higher education levels might not necessarily correlate with higher or lower prevalence rates of eating disorders.</p>
<p>Anxiety Disorders: There’s a wide spread of prevalence rates at all levels of education, suggesting that the relationship between education and anxiety disorders may be influenced by factors other than education alone.</p>
<p>Depression (%): There’s a wide spread of prevalence rates at all levels of education, suggesting that the relationship between education and Depression disorders may be influenced by factors other than education alone.</p>
<p>In general, the scatter plots show that there is no clear relationship between education and the prevalence of mental health disorders. This could indicate that other factors may be more influential in determining the prevalence of mental health disorders.</p>
<p>Relationship between ‘GDP(2022)’ and mental health disorders prevalence rates</p>
<div class="cell" data-execution_count="546">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This function will adjust the number of subplots based on the number of disorders.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_scatter_plots(dataframe, x_col, y_cols, row_col_count):</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the number of rows and columns needed for the subplots</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    total_plots <span class="op">=</span> <span class="bu">len</span>(y_cols)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    nrows <span class="op">=</span> (total_plots <span class="op">+</span> row_col_count <span class="op">-</span> <span class="dv">1</span>) <span class="op">//</span> row_col_count  <span class="co"># Ceiling division</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    ncols <span class="op">=</span> row_col_count</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create subplots</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(nrows, ncols, figsize<span class="op">=</span>(<span class="dv">15</span>, nrows <span class="op">*</span> <span class="dv">5</span>))</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> nrows <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>        axes <span class="op">=</span> [axes]  <span class="co"># Ensure axes is always a list</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>        axes <span class="op">=</span> axes.flatten()</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate scatter plots</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, y_col <span class="kw">in</span> <span class="bu">enumerate</span>(y_cols):</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>        sns.scatterplot(ax<span class="op">=</span>axes[i], data<span class="op">=</span>dataframe, x<span class="op">=</span>x_col, y<span class="op">=</span>y_col)</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>        axes[i].set_title(<span class="ss">f'</span><span class="sc">{</span>y_col<span class="sc">}</span><span class="ss"> vs </span><span class="sc">{</span>x_col<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>        axes[i].set_xlabel(x_col)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>        axes[i].set_ylabel(<span class="ss">f'Prevalence of </span><span class="sc">{</span>y_col<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Hide any unused subplots</span></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(i<span class="op">+</span><span class="dv">1</span>, <span class="bu">len</span>(axes)):</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>        axes[j].set_visible(<span class="va">False</span>)</span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Adjust layout</span></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a>gdp_col <span class="op">=</span> <span class="st">'GDP(2022)'</span></span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a>mental_health_disorders <span class="op">=</span> [</span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Schizophrenia (%)'</span>,  <span class="co"># The prevalence of schizophrenia as a percentage</span></span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Bipolar disorder (%)'</span>,  <span class="co"># The prevalence of bipolar disorder as a percentage</span></span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Eating disorders (%)'</span>,  <span class="co"># The prevalence of eating disorders as a percentage</span></span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Anxiety disorders (%)'</span> , <span class="co"># The prevalence of anxiety disorders as a percentage</span></span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Depression (%)'</span>  <span class="co"># The prevalence of depression as a percentage</span></span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Now let's use the function to create scatter plots</span></span>
<span id="cb31-41"><a href="#cb31-41" aria-hidden="true" tabindex="-1"></a>create_scatter_plots(df_mental_health, gdp_col, mental_health_disorders, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-14-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The scatter plots show that they does not appear to be a clear trend or correlation between GDP and the prevalence of these mental health problems.</p>
<p>Relationship between ‘GDP per capita’ and mental health disorders prevalence rates.</p>
<div class="cell" data-execution_count="547">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This function will adjust the number of subplots based on the number of disorders.</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_scatter_plots(dataframe, x_col, y_cols, row_col_count):</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the number of rows and columns needed for the subplots</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    total_plots <span class="op">=</span> <span class="bu">len</span>(y_cols)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    nrows <span class="op">=</span> (total_plots <span class="op">+</span> row_col_count <span class="op">-</span> <span class="dv">1</span>) <span class="op">//</span> row_col_count  <span class="co"># Ceiling division</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    ncols <span class="op">=</span> row_col_count</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create subplots</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(nrows, ncols, figsize<span class="op">=</span>(<span class="dv">15</span>, nrows <span class="op">*</span> <span class="dv">5</span>))</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> nrows <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>        axes <span class="op">=</span> [axes]  <span class="co"># Ensure axes is always a list</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>        axes <span class="op">=</span> axes.flatten()</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate scatter plots</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, y_col <span class="kw">in</span> <span class="bu">enumerate</span>(y_cols):</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>        sns.scatterplot(ax<span class="op">=</span>axes[i], data<span class="op">=</span>dataframe, x<span class="op">=</span>x_col, y<span class="op">=</span>y_col)</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>        axes[i].set_title(<span class="ss">f'</span><span class="sc">{</span>y_col<span class="sc">}</span><span class="ss"> vs </span><span class="sc">{</span>x_col<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>        axes[i].set_xlabel(x_col)</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>        axes[i].set_ylabel(<span class="ss">f'Prevalence of </span><span class="sc">{</span>y_col<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Hide any unused subplots</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(i<span class="op">+</span><span class="dv">1</span>, <span class="bu">len</span>(axes)):</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>        axes[j].set_visible(<span class="va">False</span>)</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Adjust layout</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>gdp_col <span class="op">=</span> <span class="st">'GDP_per_capita'</span></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>mental_health_disorders <span class="op">=</span> [</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Schizophrenia (%)'</span>,  <span class="co"># The prevalence of schizophrenia as a percentage</span></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Bipolar disorder (%)'</span>,  <span class="co"># The prevalence of bipolar disorder as a percentage</span></span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Eating disorders (%)'</span>,  <span class="co"># The prevalence of eating disorders as a percentage</span></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Anxiety disorders (%)'</span> , <span class="co"># The prevalence of anxiety disorders as a percentage</span></span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Depression (%)'</span>  <span class="co"># The prevalence of depression as a percentage</span></span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a><span class="co">#use the function to create scatter plots</span></span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>create_scatter_plots(df_mental_health, gdp_col, mental_health_disorders, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-15-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>As GDP per capita increases, the prevalence rates of eating disorder seems to spread out, while others don’t show a clear trend indicating a strong relationship with gdp per capita.</p>
</section>
<section id="correlation-heatmap" class="level4">
<h4 class="anchored" data-anchor-id="correlation-heatmap">Correlation Heatmap</h4>
<p>‘Income group’ and ‘Continent’ to the list of columns for the correlation matrix, which are categorical variables. The correlation matrix typically requires numerical variables. To include these categorical variables, I convert them into a numerical format using techniques such as one-hot encoding.</p>
<div class="cell" data-execution_count="548">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>correlation_columns <span class="op">=</span> [</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Schizophrenia (%)'</span>, </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Bipolar disorder (%)'</span>, </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Eating disorders (%)'</span>, </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Anxiety disorders (%)'</span>, </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Depression (%)'</span>, </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'GDP(2022)'</span>,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'average_learning_Adjusted_of_school'</span>,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'GDP_per_capita'</span>,</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'not_at_all_comfortable_speaking_anxiety_or_depression_percent'</span>,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 'Income group',</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 'Continent',</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encoding the 'Income group' and 'Continent' columns to include them in the correlation matrix</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>encoded_data <span class="op">=</span> pd.get_dummies(df_mental_health, columns<span class="op">=</span>[<span class="st">'Income group'</span>, <span class="st">'Continent'</span>])</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Updating the correlation_columns list to include the newly created one-hot encoded columns</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>new_correlation_columns <span class="op">=</span> correlation_columns <span class="op">+</span> <span class="bu">list</span>(encoded_data.columns[encoded_data.columns.<span class="bu">str</span>.startswith(<span class="st">'Income group_'</span>)]) <span class="op">+</span> <span class="bu">list</span>(encoded_data.columns[encoded_data.columns.<span class="bu">str</span>.startswith(<span class="st">'Continent_'</span>)])</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the new correlation matrix including the one-hot encoded columns</span></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>new_correlation_matrix <span class="op">=</span> encoded_data[new_correlation_columns].corr()</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a mask for the upper triangle</span></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> np.triu(np.ones_like(new_correlation_matrix, dtype<span class="op">=</span><span class="bu">bool</span>))</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up the matplotlib figure</span></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">10</span>))</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw the heatmap with the mask</span></span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>sns.heatmap(new_correlation_matrix, annot<span class="op">=</span><span class="va">True</span>, mask<span class="op">=</span>mask, fmt<span class="op">=</span><span class="st">".2f"</span>, cmap<span class="op">=</span><span class="st">'coolwarm'</span>, cbar_kws<span class="op">=</span>{<span class="st">"shrink"</span>: <span class="fl">.5</span>},cbar<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Add title</span></span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Correlation Heatmap for Mental Health Metrics with Categorical Variables'</span>)</span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the heatmap</span></span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-16-output-1.png" class="img-fluid"></p>
</div>
</div>
<p><b>Socioeconomic Factors:</b> These include GDP (2022), GDP per capita, and income groups (high, low, lower middle, upper middle). High-income groups have strong positive correlations with mental health outcomes, particularly with eating disorders (0.74), and Schizophrenia(0.58). This suggests that in high-income groups, there may be a higher reported prevalence or better diagnosis of these conditions. On the other hand, low-income groups show a moderate negative correlation with some mental health outcomes, indicating a lower reported prevalence or underdiagnosis in these groups.</p>
<p><b>Educational Factors:</b> The variable ‘average_learning_Adjusted_of_school’ shows strong positive correlations with eating disorders (0.69), and Schizophrenia(0.68). This suggests that higher education levels are associated with a higher reported prevalence of these conditions, which could be due to increased awareness and reporting in more educated populations.</p>
<p><b>Geographic Factors:</b> The geographic regions show varied correlations with mental health outcomes. For example, being in Africa has a strong negative correlation with schizophrenia (-0.53) and a moderate negative correlation with eating disorder (-0.39). In contrast, Europe shows a moderate positive correlation with eating disorders (0.43). These correlations suggest that geographic location can have a significant impact on the reporting and prevalence of mental health conditions, possibly due to cultural, environmental, or healthcare-related factors.</p>
<p>In summary, educational factors, indicated by ‘average_learning_Adjusted_of_school’, show the most consistent strong positive correlations across several mental health outcomes, suggesting that education level may be a strong predictor of mental health outcomes, potentially due to greater awareness and reporting. Socioeconomic factors, particularly income level, also show strong correlations, especially in high-income groups. Geographic factors show both strong negative and moderate positive correlations, indicating a more complex relationship with mental health outcomes that could be influenced by a variety of regional factors.</p>
</section>
</section>
<section id="eating-disorder-dataset" class="level3">
<h3 class="anchored" data-anchor-id="eating-disorder-dataset">2.Eating disorder Dataset</h3>
<section id="time-series-plot-1" class="level4">
<h4 class="anchored" data-anchor-id="time-series-plot-1">Time Series Plot:</h4>
<p>Showing the trend of eating disorder prevalence over years averaged globally between male and female.</p>
<div class="cell" data-execution_count="549">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average prevalence of eating disorders for each year across all countries</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>average_eating_disorders_per_year <span class="op">=</span> df_eating_disorder.groupby(<span class="st">'Year'</span>).mean().reset_index()</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Time Series Line Plot for the global trend</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">7</span>))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the trends for each gender and all genders combined</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>average_eating_disorders_per_year, x<span class="op">=</span><span class="st">'Year'</span>, y<span class="op">=</span><span class="st">'Eating_disorders_Male'</span>, label<span class="op">=</span><span class="st">'Male'</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>average_eating_disorders_per_year, x<span class="op">=</span><span class="st">'Year'</span>, y<span class="op">=</span><span class="st">'Eating_disorders_Female'</span>, label<span class="op">=</span><span class="st">'Female'</span>)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>average_eating_disorders_per_year, x<span class="op">=</span><span class="st">'Year'</span>, y<span class="op">=</span><span class="st">'All_gender'</span>, label<span class="op">=</span><span class="st">'All Genders'</span>)</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Global Average Prevalence of Eating Disorders Over Time'</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Average Prevalence'</span>)</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the line plot</span></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/758625183.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average_eating_disorders_per_year = df_eating_disorder.groupby('Year').mean().reset_index()</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-17-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>The line plot above shows the global average prevalence of eating disorders over time for males, females, and all genders combined. The trends can be compared to see how the prevalence has changed over the years. Eating disorders were more than twice as prevalent among females (3.8%) than males (1.5%)</p>
</section>
<section id="grouped-bar-chart" class="level4">
<h4 class="anchored" data-anchor-id="grouped-bar-chart">Grouped Bar Chart:</h4>
<p>Compare the prevalence of eating disorders between males and females across different countries. For clarity,I will take a subset of countries to compare.</p>
<div class="cell" data-execution_count="550">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomly select 10 countries for comparison</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>random_countries <span class="op">=</span> df_eating_disorder[<span class="st">'Economy'</span>].drop_duplicates().sample(<span class="dv">10</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data for the selected countries and the latest year available</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>latest_year <span class="op">=</span> df_eating_disorder[<span class="st">'Year'</span>].<span class="bu">max</span>()</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>comparison_data <span class="op">=</span> df_eating_disorder[(df_eating_disorder[<span class="st">'Economy'</span>].isin(random_countries)) <span class="op">&amp;</span> (df_eating_disorder[<span class="st">'Year'</span>] <span class="op">==</span> latest_year)]</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data for grouped bar chart</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>comparison_data[<span class="st">'Economy'</span>] <span class="op">=</span> comparison_data[<span class="st">'Economy'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>comparison_data[<span class="st">'Economy'</span>].cat.set_categories(random_countries, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>comparison_data.sort_values(<span class="st">'Economy'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine the positions of the bars</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>pos <span class="op">=</span> np.arange(<span class="bu">len</span>(random_countries))</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>bar_width <span class="op">=</span> <span class="fl">0.4</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the bar chart</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">7</span>))</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for males</span></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>plt.bar(pos <span class="op">-</span> bar_width<span class="op">/</span><span class="dv">2</span>, comparison_data[<span class="st">'Eating_disorders_Male'</span>], bar_width, color<span class="op">=</span><span class="st">'lightblue'</span>, label<span class="op">=</span><span class="st">'Male'</span>)</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for females</span></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>plt.bar(pos <span class="op">+</span> bar_width<span class="op">/</span><span class="dv">2</span>, comparison_data[<span class="st">'Eating_disorders_Female'</span>], bar_width, color<span class="op">=</span><span class="st">'lightgreen'</span>, label<span class="op">=</span><span class="st">'Female'</span>)</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="ss">f'Comparison of Eating Disorders Prevalence by Gender in </span><span class="sc">{</span>latest_year<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Economy'</span>)</span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Prevalence of Eating Disorders'</span>)</span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a>plt.xticks(pos, random_countries, rotation<span class="op">=</span><span class="dv">45</span>, ha<span class="op">=</span><span class="st">'right'</span>)</span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-32"><a href="#cb36-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the bar chart</span></span>
<span id="cb36-33"><a href="#cb36-33" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb36-34"><a href="#cb36-34" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/2505907414.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comparison_data['Economy'] = comparison_data['Economy'].astype('category')
/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/2505907414.py:10: FutureWarning: The `inplace` parameter in pandas.Categorical.set_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  comparison_data['Economy'].cat.set_categories(random_countries, inplace=True)
/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/2505907414.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comparison_data.sort_values('Economy', inplace=True)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-18-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>The bar chart above compares the prevalence of eating disorders between males (in light blue) and females (in pink) for a randomly selected subset of 10 countries in the latest year available in the dataset.</p>
</section>
<section id="box-plot" class="level4">
<h4 class="anchored" data-anchor-id="box-plot">Box plot</h4>
<section id="identifying-outliers" class="level5">
<h5 class="anchored" data-anchor-id="identifying-outliers">Identifying Outliers</h5>
<p>looking for countries with prevalence rates that are significantly higher or lower than the global average for year 2019 for example</p>
<div class="cell" data-execution_count="551">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For the trend analysis, let's select the most recent year available for all countries</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>latest_year <span class="op">=</span> df_eating_disorder[<span class="st">'Year'</span>].<span class="bu">max</span>()</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Now, let's prepare the data for that year to identify outliers</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>latest_data <span class="op">=</span> df_eating_disorder[df_eating_disorder[<span class="st">'Year'</span>] <span class="op">==</span> latest_year]</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating box plots for male and female prevalence rates to identify outliers</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">8</span>))</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot for male prevalence</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>sns.boxplot(y<span class="op">=</span>latest_data[<span class="st">'Eating_disorders_Male'</span>])</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Male Eating Disorder Prevalence Rate in '</span> <span class="op">+</span> <span class="bu">str</span>(latest_year))</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot for female prevalence</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>sns.boxplot(y<span class="op">=</span>latest_data[<span class="st">'Eating_disorders_Female'</span>])</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Female Eating Disorder Prevalence Rate in '</span> <span class="op">+</span> <span class="bu">str</span>(latest_year))</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a><span class="co"># We can also calculate the summary statistics for each gender</span></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>male_stats <span class="op">=</span> latest_data[<span class="st">'Eating_disorders_Male'</span>].describe()</span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>female_stats <span class="op">=</span> latest_data[<span class="st">'Eating_disorders_Female'</span>].describe()</span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a>(male_stats, female_stats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-19-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display" data-execution_count="551">
<pre><code>(count    214.000000
 mean       0.131786
 std        0.074714
 min        0.033747
 25%        0.081544
 50%        0.111878
 75%        0.156691
 max        0.672270
 Name: Eating_disorders_Male, dtype: float64,
 count    214.000000
 mean       0.299529
 std        0.230234
 min        0.057713
 25%        0.141947
 50%        0.210908
 75%        0.398235
 max        1.395754
 Name: Eating_disorders_Female, dtype: float64)</code></pre>
</div>
</div>
<p>Male Eating Disorder Prevalence Rate:</p>
<p>The median prevalence rate is approximately 0.11%. The range of prevalence rates is quite broad, with the lowest around 0.03% and the highest at about 0.67%. The interquartile range (middle 50% of the data) spans from approximately 0.08% to 0.16%, indicating that half of the reported rates fall within this range.</p>
<p>Female Eating Disorder Prevalence Rate:</p>
<p>The median prevalence rate is approximately 0.21%, which is notably higher than that of males. The prevalence rates for females also show a broad range, from about 0.06% to 1.40%. The interquartile range for females is wider than for males, ranging from about 0.14% to 0.40%, reflecting greater variability in the rates reported for females.</p>
<p>Outlier Identification:</p>
<p>For males, any country with a prevalence rate significantly higher than 0.16% could be considered an outlier. For females, countries with rates above 0.40% would be outliers, with the maximum reported rate being quite extreme at 1.40%.</p>
</section>
<section id="remove-the-outliers" class="level5">
<h5 class="anchored" data-anchor-id="remove-the-outliers">Remove the outliers</h5>
<div class="cell" data-execution_count="552">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the interquartile range for males</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>Q1_male <span class="op">=</span> df_eating_disorder[<span class="st">'Eating_disorders_Male'</span>].quantile(<span class="fl">0.25</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>Q3_male <span class="op">=</span> df_eating_disorder[<span class="st">'Eating_disorders_Male'</span>].quantile(<span class="fl">0.75</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>IQR_male <span class="op">=</span> Q3_male <span class="op">-</span> Q1_male</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>lower_bound_male <span class="op">=</span> Q1_male <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> IQR_male</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>upper_bound_male <span class="op">=</span> Q3_male <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> IQR_male</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove outliers for males</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>latest_data_no_outliers_male <span class="op">=</span> df_eating_disorder[(df_eating_disorder[<span class="st">'Eating_disorders_Male'</span>] <span class="op">&gt;=</span> lower_bound_male) <span class="op">&amp;</span> </span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>                                           (df_eating_disorder[<span class="st">'Eating_disorders_Male'</span>] <span class="op">&lt;=</span> upper_bound_male)]</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the interquartile range for females</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>Q1_female <span class="op">=</span> df_eating_disorder[<span class="st">'Eating_disorders_Female'</span>].quantile(<span class="fl">0.25</span>)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>Q3_female <span class="op">=</span> df_eating_disorder[<span class="st">'Eating_disorders_Female'</span>].quantile(<span class="fl">0.75</span>)</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>IQR_female <span class="op">=</span> Q3_female <span class="op">-</span> Q1_female</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>lower_bound_female <span class="op">=</span> Q1_female <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> IQR_female</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>upper_bound_female <span class="op">=</span> Q3_female <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> IQR_female</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove outliers for females</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>latest_data_no_outliers_female <span class="op">=</span> latest_data[(df_eating_disorder[<span class="st">'Eating_disorders_Female'</span>] <span class="op">&gt;=</span> lower_bound_female) <span class="op">&amp;</span> </span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>                                             (df_eating_disorder[<span class="st">'Eating_disorders_Female'</span>] <span class="op">&lt;=</span> upper_bound_female)]</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Now let's plot the data without outliers</span></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">8</span>))</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot for male prevalence without outliers</span></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>sns.boxplot(y<span class="op">=</span>latest_data_no_outliers_male[<span class="st">'Eating_disorders_Male'</span>])</span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Male Eating Disorder Prevalence Rate in '</span> <span class="op">+</span> <span class="st">' (No Outliers)'</span>)</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot for female prevalence without outliers</span></span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a>sns.boxplot(y<span class="op">=</span>latest_data_no_outliers_female[<span class="st">'Eating_disorders_Female'</span>])</span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Female Eating Disorder Prevalence Rate in '</span> <span class="op">+</span> <span class="st">' (No Outliers)'</span>)</span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a><span class="co">#save the data sets</span></span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a><span class="co"># latest_data.to_csv('./Data/eating_disorder_male_female_rm_outliers.csv',index=False)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/2046586742.py:20: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  latest_data_no_outliers_female = latest_data[(df_eating_disorder['Eating_disorders_Female'] &gt;= lower_bound_female) &amp;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-20-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="heatmap" class="level4">
<h4 class="anchored" data-anchor-id="heatmap">Heatmap</h4>
<p>Visualizing the prevalence of eating disorders in US and years in a color-coded format.</p>
<div class="cell" data-execution_count="553">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For the heatmap , select all years of data for US only.</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>us_data <span class="op">=</span> df_eating_disorder[df_eating_disorder[<span class="st">'Economy'</span>] <span class="op">==</span> <span class="st">'United States'</span>].pivot(<span class="st">'Year'</span>, <span class="st">'Code'</span>, <span class="st">'All_gender'</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>sns.heatmap(us_data, cmap<span class="op">=</span><span class="st">"YlOrRd"</span>, linewidths<span class="op">=</span><span class="fl">.5</span>, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">".2f"</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Heatmap of Eating Disorders Prevalence Across Years in US'</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Country Code'</span>)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Year'</span>)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the heatmap</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/671262145.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  us_data = df_eating_disorder[df_eating_disorder['Economy'] == 'United States'].pivot('Year', 'Code', 'All_gender')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-21-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>The heatmap above visualizes the prevalence of eating disorders across different years in US.</p>
<p>In years 1993 and 2012 show the highest prevalence rates. From 2013 onwards, there appears to be a slight decrease in prevalence, with rates consistently around 0.42% to 0.43%.</p>
</section>
</section>
<section id="age-when-first-have-depression-or-anxiety-data" class="level3">
<h3 class="anchored" data-anchor-id="age-when-first-have-depression-or-anxiety-data">3.Age when first have depression or anxiety Data</h3>
<section id="pie-chart" class="level4">
<h4 class="anchored" data-anchor-id="pie-chart">Pie chart</h4>
<p>Showing the distribution of age categories for the onset of anxiety or depression for the “World” entity, I’ll first filter the dataset for the ‘World’ entity, and then plot the data.</p>
<div class="cell" data-execution_count="554">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data for the 'World' entity</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>world_data <span class="op">=</span> df_age_first_depression[df_age_first_depression[<span class="st">'Entity'</span>] <span class="op">==</span> <span class="st">'World'</span>]</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">8</span>))</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>plt.pie(world_data[<span class="st">'Percentage'</span>], labels<span class="op">=</span>world_data[<span class="st">'Age'</span>], autopct<span class="op">=</span><span class="st">'</span><span class="sc">%1.1f%%</span><span class="st">'</span>, startangle<span class="op">=</span><span class="dv">140</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Age Categories for First Anxiety or Depression in the World'</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'equal'</span>)  <span class="co"># Equal aspect ratio ensures that pie is drawn as a circle.</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the pie chart</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-22-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The largest segment of the chart, making up 34.9%, is unspecified and labeled “Don’t know/Refused,” indicating a significant portion of respondents either did not know or refused to provide their age at first experience of anxiety or depression.</p>
<p>The second-largest group is individuals aged 20–29, representing 22.2% of the distribution. This suggests that early adulthood is a common time for individuals to experience their first instance of these mental health issues.</p>
<p>Those aged 30–39 make up 12.5% of the distribution, while individuals aged 40 and over account for 11.4%.</p>
<p>Adolescents aged 13–19 represent 11.5% of the distribution, indicating that the onset of anxiety or depression can also begin during teenage years.</p>
<p>The smallest identified age group is children under the age of 13, at 7.5%, which highlights that while less common, young children can also experience these mental health issues.</p>
<p>Overall, the data suggests that the onset of anxiety or depression is reported most frequently during the ages of 20–29 and that there’s a notable amount of uncertainty or unwillingness to provide information regarding the age of first experience with these conditions.</p>
</section>
<section id="heatmap-1" class="level4">
<h4 class="anchored" data-anchor-id="heatmap-1">Heatmap</h4>
<p>a.Visualize the relationship between entities and age groups</p>
<div class="cell" data-execution_count="555">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a pivot table for the heatmap</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>heatmap_data <span class="op">=</span> df_age_first_depression.pivot(<span class="st">"Entity"</span>, <span class="st">"Age"</span>, <span class="st">"Percentage"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Heatmap: Visualize the percentage of individuals by entity and age category</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">10</span>))</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>heatmap <span class="op">=</span> sns.heatmap(heatmap_data, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">".1f"</span>, linewidths<span class="op">=</span><span class="fl">.5</span>, cmap<span class="op">=</span><span class="st">"YlGnBu"</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Heatmap of Percentage by Entity and Age Category for First Anxiety or Depression'</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Age Category'</span>)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Entity'</span>)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the heatmap</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/px/bhxss9d10zs_wzsv0ck6sb200000gn/T/ipykernel_19940/3650547391.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  heatmap_data = df_age_first_depression.pivot("Entity", "Age", "Percentage")</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-23-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="stacked-bar-chart" class="level4">
<h4 class="anchored" data-anchor-id="stacked-bar-chart">Stacked bar chart</h4>
<p>Grouping the data by Entity and visualizing the distribution of the Percentage across different Age brackets.</p>
<div class="cell" data-execution_count="556">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Stacked Bar Chart: Create a crosstab to prepare data for the stacked plot</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>stacked_data <span class="op">=</span> pd.crosstab(index<span class="op">=</span>df_age_first_depression[<span class="st">'Entity'</span>], columns<span class="op">=</span>df_age_first_depression[<span class="st">'Age'</span>], values<span class="op">=</span>df_age_first_depression[<span class="st">'Percentage'</span>], aggfunc<span class="op">=</span><span class="st">'sum'</span>, normalize<span class="op">=</span><span class="st">'index'</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the stacked bar chart</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>stacked_data.plot(kind<span class="op">=</span><span class="st">'bar'</span>, stacked<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>), colormap<span class="op">=</span><span class="st">'viridis'</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Stacked Bar Chart of Age Categories for First Anxiety or Depression by Entity'</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Entity'</span>)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Percentage'</span>)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">'Age Category'</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.05</span>, <span class="dv">1</span>), loc<span class="op">=</span><span class="st">'upper left'</span>)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>, ha<span class="op">=</span><span class="st">'right'</span>)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the stacked bar chart</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="Exploration_files/figure-html/cell-24-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>High Uncertainty or Non-disclosure: ‘Don’t know/Refused’ responses are notably high across all entities, with Africa recording the highest at 42.7% ,lower-middle income countries at 40.6% and Europe the lowest at 14.5%. This indicates a significant amount of data is either not known or not disclosed.</p>
<p>High-Income Countries: except for ‘Don’t know/Refused’, The highest ratios are observed in the ’Ages 13_19’and lowest in the Age &lt; 13</p>
<p>Upper-middle income countries: except for ‘Don’t know/Refused’, The ratios are more balanced across the age categories, with the lowest ratio STILL in age &lt;13.</p>
<p>lower-middle income countries: except for ‘Don’t know/Refused’,The highest ratios are observed in the ‘Ages 20_29’ and it is almost 3 times higher than other age categories.</p>
<p>Europe: The ratios are more balanced across the age categories, with the lowest ratio in age &lt;13.</p>
<p>Africa and Asia: The ratios are Highest in the ‘Ages 20_29’ and lowest in the Age &lt; 13, but the ratio in Asia is higher than Africa.</p>
</section>
</section>
</section>
<section id="hypothesis-generation" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-generation">Hypothesis Generation</h2>
<section id="age-first-depression-or-anxiety-data" class="level3">
<h3 class="anchored" data-anchor-id="age-first-depression-or-anxiety-data">Age First Depression or Anxiety Data</h3>
<ul>
<li><p>The cultural, economic, and social environments in high-income countries might contribute to an earlier age of onset (The highest ratios are observed in the ’Ages 13_19) for anxiety or depression.</p></li>
<li><p>In regions with lower-middle-income levels, the onset of anxiety or depression might occur later, potentially due to different life stressors or lower levels of mental health awareness and reporting.</p></li>
</ul>
</section>
<section id="eating-disorder-dataset-1" class="level3">
<h3 class="anchored" data-anchor-id="eating-disorder-dataset-1">Eating disorder Dataset</h3>
<ul>
<li><p>The prevalence of eating disorders is higher in countries with higher GDP per capita, which could reflect better diagnostic capabilities or different societal pressures.</p></li>
<li><p>There may be significant differences in the prevalence of eating disorders between genders across different countries, potentially reflecting cultural, social, or biological factors.</p></li>
</ul>
</section>
<section id="mental-health-dataset-1" class="level3">
<h3 class="anchored" data-anchor-id="mental-health-dataset-1">Mental Health Dataset</h3>
<ul>
<li><p>Educational outcomes may be associated with the prevalence or reporting of certain mental health conditions, such as schizophrenia and eating disorders.</p></li>
<li><p>The correlations between different mental health conditions suggest the possibility of common underlying risk factors or increased comorbidity.</p></li>
</ul>
</section>
</section>
<section id="report-and-discuss-methods-and-findings" class="level2">
<h2 class="anchored" data-anchor-id="report-and-discuss-methods-and-findings">Report and Discuss methods and findings</h2>
<section id="age-first-depression-or-anxiety-data-1" class="level5">
<h5 class="anchored" data-anchor-id="age-first-depression-or-anxiety-data-1">Age First Depression or Anxiety Data</h5>
<ol type="1">
<li><p>The largest segment of the data, making up 34.9%, is unspecified and labeled “Don’t know/Refused,” indicating a significant portion of respondents either did not know or refused to provide their age at first experience of anxiety or depression.(High Uncertainty or Non-disclosure: ‘Don’t know/Refused’ responses are notably high across all entities, with Africa recording the highest at 42.7% ,lower-middle income countries at 40.6% and Europe the lowest at 14.5%. This indicates a significant amount of data is either not known or not disclosed.) The second-largest group is individuals aged 20–29, representing 22.2% of the distribution. This suggests that early adulthood is a common time for individuals to experience their first instance of these mental health issues.Those aged 30–39 make up 12.5% of the distribution, while individuals aged 40 and over account for 11.4%.Adolescents aged 13–19 represent 11.5% of the distribution, indicating that the onset of anxiety or depression can also begin during teenage years.The smallest identified age group is children under the age of 13, at 7.5%, which highlights that while less common, young children can also experience these mental health issues. Overall, the data suggests that the onset of anxiety or depression is reported most frequently during the ages of 20–29 and that there’s a notable amount of uncertainty or unwillingness to provide information regarding the age of first experience with these conditions.</p></li>
<li><p>High-Income Countries: except for ‘Don’t know/Refused’, The highest ratios are observed in the ‘Ages 13_19’and lowest in the Age &lt; 13; Upper-middle income countries: except for ’Don’t know/Refused’, The ratios are more balanced across the age categories, with the lowest ratio STILL in age &lt;13; lower-middle income countries: except for ‘Don’t know/Refused’,The highest ratios are observed in the ‘Ages 20_29’ and it is almost 3 times higher than other age categories; Europe: The ratios are more balanced across the age categories, with the lowest ratio in age &lt;13; Africa and Asia: The ratios are Highest in the ‘Ages 20_29’ and lowest in the Age &lt; 13, but the ratio in Asia is higher than Africa.</p></li>
</ol>
</section>
<section id="eating-disorder-dataset-2" class="level5">
<h5 class="anchored" data-anchor-id="eating-disorder-dataset-2">Eating disorder Dataset</h5>
<ol type="1">
<li><p>The prevalence of eating disorders is significantly higher in females than in males, which aligns with the general understanding of these conditions.</p></li>
<li><p>The variability in prevalence rates among females is greater, indicating that eating disorders in females may be more influenced by a variety of factors, possibly including cultural aspects, societal pressures, or biological predispositions.</p></li>
<li><p>The global average prevalence of eating disorders over time for males, females, and all genders combined is growing up.</p></li>
</ol>
</section>
<section id="mental-health-dataset-2" class="level4">
<h4 class="anchored" data-anchor-id="mental-health-dataset-2">Mental Health Dataset</h4>
<ol type="1">
<li><p>Educational factors, indicated by ‘average_learning_Adjusted_of_school’, show the most consistent strong positive correlations across several mental health outcomes, suggesting that education level may be a strong predictor of mental health outcomes, potentially due to greater awareness and reporting.</p></li>
<li><p>Socioeconomic factors, particularly income level, also show strong correlations, especially in high-income groups.</p></li>
<li><p>Geographic factors show both strong negative and moderate positive correlations, indicating a more complex relationship with mental health outcomes that could be influenced by a variety of regional factors.</p></li>
</ol>
</section>
</section>
<section id="tools-and-software" class="level2">
<h2 class="anchored" data-anchor-id="tools-and-software">Tools and Software</h2>
<ul>
<li>Pandas: For data manipulation and analysis.</li>
<li>Matplotlib: For creating the bar chart visualization.</li>
<li>Seaborn: Although not used in the last plot, it is an excellent tool for creating heatmaps and other complex visualizations.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>